import type { Metadata } from "next";
import localFont from 'next/font/local';
import "./globals.css";

// CHANGED: The path now correctly points to the sibling 'fonts' folder
const satoshi = localFont({
  src: './fonts/Satoshi-Variable.woff2',
  display: 'swap',
  variable: '--font-satoshi',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={satoshi.variable}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}